name: GraphAr Java CI

on:
  # Trigger the workflow on push or pull request,
  # but only for the main branch
  push:
    branches:
      - main
    paths:
      - 'java/**'
      - '.github/workflows/java.yml'
  pull_request:
    branches:
      - main
    paths:
      - 'java/**'
      - '.github/workflows/java.yml'

concurrency:
  group: ${{ github.repository }}-${{ github.event.number || github.head_ref || github.sha }}-${{ github.workflow }}
  cancel-in-progress: true

jobs:
  GraphAr-java:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
          
      - name: Install dependencies
        run: |
          # install the latest arrow deb to test arrow
          wget -c https://apache.jfrog.io/artifactory/arrow/"$(lsb_release --id --short | tr 'A-Z' 'a-z')"/apache-arrow-apt-source-latest-$(lsb_release --codename --short).deb \
            -P /tmp/
          sudo apt-get install -y /tmp/apache-arrow-apt-source-latest-"$(lsb_release --codename --short)".deb
          sudo apt-get update -y
          # TODO: ISSUE-241
          sudo apt install -y libarrow-dev=14.0.1-1 \
                            libarrow-dataset-dev=14.0.1-1 \
                            libarrow-acero-dev=14.0.1-1 \
                            libparquet-dev=14.0.1-1
          sudo apt-get install libcurl4-openssl-dev -y
          sudo apt-get install llvm-11 clang-11 lld-11 libclang-11-dev libz-dev -y
          
      - name: Code Format Check
        run: |
          export JAVA_HOME=${JAVA_HOME_11_X64}
          pushd java 
          mvn spotless:check
          popd

      - name: Run test
        run: |
          # Temporarily using Java 8, related issue: https://github.com/alibaba/GraphAr/issues/277
          export JAVA_HOME=${JAVA_HOME_8_X64}
          export LLVM11_HOME=/usr/lib/llvm-11
          pushd java
          mvn test -Dspotless.check.skip=true
          popd
